package com.jongs.AnalisadorLex.Lex;

/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexer.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\36\1\46\1\50\1\47\1\47\22\0\1\36\1\0\1\62"+
    "\1\45\4\0\1\53\1\54\2\0\1\63\3\0\12\42\1\23\1\0"+
    "\1\60\1\61\1\57\2\0\2\37\1\22\1\34\1\24\3\37\1\27"+
    "\5\37\1\32\3\37\1\30\1\26\6\37\1\55\1\0\1\56\1\0"+
    "\1\41\1\0\1\5\1\31\1\14\1\20\1\4\1\33\1\40\1\17"+
    "\1\11\1\35\1\40\1\6\1\3\1\12\1\2\1\40\1\25\1\21"+
    "\1\1\1\15\1\10\1\7\1\44\1\13\1\16\1\40\1\51\1\0"+
    "\1\52\7\0\1\50\u05da\0\12\43\206\0\12\43\306\0\12\43\u019c\0"+
    "\12\43\166\0\12\43\166\0\12\43\166\0\12\43\166\0\12\43\166\0"+
    "\12\43\166\0\12\43\166\0\12\43\166\0\12\43\166\0\12\43\140\0"+
    "\12\43\166\0\12\43\106\0\12\43\u0116\0\12\43\106\0\12\43\u0746\0"+
    "\12\43\46\0\12\43\u012c\0\12\43\200\0\12\43\246\0\12\43\6\0"+
    "\12\43\266\0\12\43\126\0\12\43\206\0\12\43\6\0\12\43\u03ce\0"+
    "\1\50\1\50\u85f6\0\12\43\u02a6\0\12\43\46\0\12\43\306\0\12\43"+
    "\26\0\12\43\126\0\12\43\u0196\0\12\43\u5316\0\12\43\u0586\0\12\43"+
    "\u0bbc\0\12\43\200\0\12\43\74\0\12\43\220\0\12\43\u0116\0\12\43"+
    "\u0156\0\12\43\166\0\12\43\u0176\0\12\43\146\0\12\43\146\0\12\43"+
    "\u01a6\0\12\43\u0366\0\12\43\u4e06\0\12\43\346\0\12\43\u6c74\0\62\43"+
    "\u1150\0\12\43\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u16b5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\15\2\6\3\1\1\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\3\0\1\22\15\0\1\3\1\0\2\23"+
    "\4\3\1\15\1\24\1\25\3\0\1\26\1\27\1\0"+
    "\1\30\1\31\2\0\1\32\3\0\2\3\1\0\4\3"+
    "\1\33\1\34\4\0\1\35\1\36\5\3\1\37\1\0"+
    "\1\40\1\41\5\3\1\0\1\42\4\3\1\43\22\3"+
    "\1\44\2\3\1\45\1\3\1\46\3\3\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c"+
    "\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac"+
    "\0\u04e0\0\64\0\64\0\64\0\64\0\64\0\64\0\u0514"+
    "\0\u0548\0\64\0\64\0\u057c\0\u05b0\0\u05e4\0\u0618\0\64"+
    "\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8"+
    "\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\64\0\64\0\64"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\64\0\64\0\u0b2c\0\64\0\64"+
    "\0\u0b60\0\u0b94\0\64\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98"+
    "\0\u0958\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\64\0\64\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\64\0\u0bfc\0\u0e6c\0\u0ea0\0\u0ed4"+
    "\0\u0f08\0\u0f3c\0\u0d9c\0\u0f70\0\64\0\u0b94\0\u0fa4\0\u0fd8"+
    "\0\u100c\0\u1040\0\u1074\0\u10a8\0\64\0\u10dc\0\u1110\0\u1144"+
    "\0\u1178\0\64\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0"+
    "\0\u12e4\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450"+
    "\0\u1484\0\u14b8\0\u14ec\0\u1520\0\64\0\u1554\0\u1588\0\64"+
    "\0\u15bc\0\64\0\u15f0\0\u1624\0\u1658\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\2\1\11\1\12\1\13\1\2\1\14\1\2\1\15"+
    "\1\2\1\16\1\17\1\2\1\20\1\2\1\21\1\22"+
    "\1\23\1\2\1\21\1\2\1\24\1\2\1\25\1\21"+
    "\2\2\1\26\2\2\1\27\1\30\1\31\1\0\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\65\0\1\45\1\46\73\0\1\47\6\0"+
    "\1\50\22\0\1\51\24\0\1\52\3\0\1\53\65\0"+
    "\1\54\56\0\1\55\3\0\1\56\56\0\1\57\57\0"+
    "\1\60\64\0\1\61\62\0\1\62\101\0\1\63\51\0"+
    "\1\64\76\0\1\65\44\0\5\21\1\66\14\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\22\21\1\0\1\21\1\72\10\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\22\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\11\21\1\73"+
    "\10\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\20\0\7\21\1\74\12\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\10\21\1\75"+
    "\11\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\55\0\1\25\10\0\1\25\56\0\1\26\21\0"+
    "\46\27\3\0\13\27\46\0\2\30\52\0\1\25\7\0"+
    "\1\30\1\31\75\0\1\76\63\0\1\77\40\0\1\44"+
    "\10\0\1\44\26\0\1\100\54\0\1\101\66\0\1\102"+
    "\63\0\1\103\70\0\1\104\62\0\1\105\56\0\1\106"+
    "\64\0\1\107\75\0\1\110\51\0\1\111\56\0\22\112"+
    "\1\0\12\112\1\0\2\112\1\0\1\112\1\0\1\112"+
    "\34\0\1\113\66\0\1\103\50\0\1\114\57\0\1\115"+
    "\115\0\1\116\31\0\4\21\1\117\15\21\1\0\12\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\41\0\1\120"+
    "\1\0\1\120\1\0\3\120\1\0\1\120\1\0\1\120"+
    "\2\0\1\120\25\0\22\121\1\0\12\121\1\0\2\121"+
    "\1\0\1\70\1\71\1\121\61\0\2\71\21\0\7\21"+
    "\1\122\12\21\1\0\12\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\17\21\1\123\2\21\1\0\12\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\20\0\22\21"+
    "\1\0\5\21\1\124\4\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\1\125\21\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\23\0\1\126\75\0"+
    "\1\127\70\0\1\130\54\0\1\131\57\0\1\132\54\0"+
    "\22\112\1\0\6\112\1\133\3\112\1\0\2\112\1\0"+
    "\1\112\1\0\1\112\34\0\1\134\47\0\22\135\1\0"+
    "\12\135\1\0\2\135\1\0\1\135\1\0\1\135\20\0"+
    "\1\103\63\0\1\136\21\21\1\0\12\21\1\0\2\21"+
    "\1\67\1\70\1\71\1\21\20\0\22\120\1\0\12\120"+
    "\1\0\2\120\1\67\2\0\1\120\20\0\10\21\1\137"+
    "\11\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\20\0\10\21\1\140\11\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\21\21\1\141"+
    "\1\0\12\21\1\0\2\21\1\67\1\70\1\71\1\21"+
    "\20\0\22\21\1\0\11\21\1\142\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\22\143\1\0\12\143\1\0"+
    "\2\143\3\0\1\143\34\0\1\144\52\0\1\145\60\0"+
    "\22\112\1\0\6\112\1\133\1\146\2\112\1\0\2\112"+
    "\1\0\1\112\1\0\1\112\20\0\1\147\21\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\6\21\1\150\13\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\6\21\1\151\13\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\5\21\1\152\14\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\1\21\1\153\20\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\25\0"+
    "\1\154\56\0\22\21\1\155\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\4\21\1\156\15\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\10\21\1\157\11\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\4\21\1\160\15\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\10\21\1\161\11\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\35\0\1\162\46\0\5\21\1\163"+
    "\14\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\20\0\17\21\1\164\2\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\1\165\21\21"+
    "\1\0\12\21\1\0\2\21\1\67\1\70\1\71\1\21"+
    "\20\0\11\21\1\166\10\21\1\0\12\21\1\0\2\21"+
    "\1\67\1\70\1\71\1\21\20\0\3\21\1\167\16\21"+
    "\1\0\12\21\1\0\2\21\1\67\1\70\1\71\1\21"+
    "\20\0\7\21\1\170\12\21\1\0\12\21\1\0\2\21"+
    "\1\67\1\70\1\71\1\21\20\0\1\171\21\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\14\21\1\172\5\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\11\21\1\173\10\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\4\21\1\174\15\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\22\21\1\0\6\21\1\175"+
    "\3\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\21\21\1\176\1\0\12\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\14\21\1\177\5\21\1\0\12\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\20\0\5\21"+
    "\1\200\14\21\1\0\12\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\22\21\1\0\7\21\1\201\2\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\20\0\5\21"+
    "\1\202\14\21\1\0\12\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\22\21\1\0\2\21\1\203\7\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\20\0\1\204"+
    "\21\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\20\0\22\21\1\205\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\4\21\1\206\15\21\1\0"+
    "\12\21\1\0\2\21\1\67\1\70\1\71\1\21\20\0"+
    "\1\21\1\207\20\21\1\0\12\21\1\0\2\21\1\67"+
    "\1\70\1\71\1\21\20\0\22\21\1\210\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\1\211\21\21"+
    "\1\0\12\21\1\0\2\21\1\67\1\70\1\71\1\21"+
    "\20\0\22\21\1\212\12\21\1\0\2\21\1\67\1\70"+
    "\1\71\1\21\20\0\1\213\21\21\1\0\12\21\1\0"+
    "\2\21\1\67\1\70\1\71\1\21\20\0\3\21\1\214"+
    "\16\21\1\0\12\21\1\0\2\21\1\67\1\70\1\71"+
    "\1\21\20\0\1\215\21\21\1\0\12\21\1\0\2\21"+
    "\1\67\1\70\1\71\1\21\20\0\22\21\1\216\12\21"+
    "\1\0\2\21\1\67\1\70\1\71\1\21\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5772];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\27\1\6\11\2\1\2\11\1\1\3\0"+
    "\1\11\15\0\1\1\1\0\6\1\3\11\3\0\2\11"+
    "\1\0\2\11\2\0\1\11\3\0\2\1\1\0\4\1"+
    "\2\11\4\0\1\11\7\1\1\0\1\11\6\1\1\0"+
    "\1\11\4\1\1\11\22\1\1\11\2\1\1\11\1\1"+
    "\1\11\3\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer string = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 396) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF, "EOF");
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /**/
            } 
            // fall through
          case 40: break;
          case 2: 
            { throw new Error("Caractere inválido <"+ yytext()+">\n na linha <"+ yyline + ">\n coluna < "+ yycolumn + ">");
            } 
            // fall through
          case 41: break;
          case 3: 
            { return symbol (sym.CLASS_IDENTIFIERS, yytext());
            } 
            // fall through
          case 42: break;
          case 4: 
            { return symbol (sym.CARDINALITY, yytext());
            } 
            // fall through
          case 43: break;
          case 5: 
            { return symbol (sym.COMMENT, yytext());
            } 
            // fall through
          case 44: break;
          case 6: 
            { return symbol (sym.BROKEN_LINE, yytext());
            } 
            // fall through
          case 45: break;
          case 7: 
            { return symbol (sym.LEFT_BRACE, yytext());
            } 
            // fall through
          case 46: break;
          case 8: 
            { return symbol (sym.RIGHT_BRACE, yytext());
            } 
            // fall through
          case 47: break;
          case 9: 
            { return symbol (sym.LEFT_PAREN, yytext());
            } 
            // fall through
          case 48: break;
          case 10: 
            { return symbol (sym.RIGHT_PAREN, yytext());
            } 
            // fall through
          case 49: break;
          case 11: 
            { return symbol (sym.LEFT_BRACKET, yytext());
            } 
            // fall through
          case 50: break;
          case 12: 
            { return symbol (sym.RIGHT_BRACKET, yytext());
            } 
            // fall through
          case 51: break;
          case 13: 
            { return symbol (sym.GREATER_THAN, yytext());
            } 
            // fall through
          case 52: break;
          case 14: 
            { return symbol (sym.LESS_THAN, yytext());
            } 
            // fall through
          case 53: break;
          case 15: 
            { return symbol (sym.EQUAL, yytext());
            } 
            // fall through
          case 54: break;
          case 16: 
            { return symbol (sym.DOUBLE_QUOTE, yytext());
            } 
            // fall through
          case 55: break;
          case 17: 
            { return symbol (sym.COMMA, yytext());
            } 
            // fall through
          case 56: break;
          case 18: 
            { return symbol (sym.OR, yytext());
            } 
            // fall through
          case 57: break;
          case 19: 
            { return symbol (sym.INDIVIDUAL_NAME, yytext());
            } 
            // fall through
          case 58: break;
          case 20: 
            { return symbol (sym.EQUAL_LESS_THAN, yytext());
            } 
            // fall through
          case 59: break;
          case 21: 
            { return symbol(sym.SSN, yytext());
            } 
            // fall through
          case 60: break;
          case 22: 
            { return symbol (sym.MAX, yytext());
            } 
            // fall through
          case 61: break;
          case 23: 
            { return symbol(sym.MIN, yytext());
            } 
            // fall through
          case 62: break;
          case 24: 
            { return symbol(sym.ALL, yytext());
            } 
            // fall through
          case 63: break;
          case 25: 
            { return symbol (sym.AND, yytext());
            } 
            // fall through
          case 64: break;
          case 26: 
            { return symbol (sym.NOT, yytext());
            } 
            // fall through
          case 65: break;
          case 27: 
            { return symbol(sym.SOME, yytext());
            } 
            // fall through
          case 66: break;
          case 28: 
            { return symbol (sym.ONLY, yytext());
            } 
            // fall through
          case 67: break;
          case 29: 
            { return symbol (sym.THAT, yytext());
            } 
            // fall through
          case 68: break;
          case 30: 
            { return symbol (sym.PROPERTY_IDENTIFIERS_HAS, yytext());
            } 
            // fall through
          case 69: break;
          case 31: 
            { return symbol (sym.DATA_TYPE, yytext());
            } 
            // fall through
          case 70: break;
          case 32: 
            { return symbol(sym.VALUE, yytext());
            } 
            // fall through
          case 71: break;
          case 33: 
            { return symbol (sym.PROPERTY_IDENTIFIERS_IS, yytext());
            } 
            // fall through
          case 72: break;
          case 34: 
            { return symbol (sym.CLASS_COLON, yytext());
            } 
            // fall through
          case 73: break;
          case 35: 
            { return symbol (sym.EXACTLY, yytext());
            } 
            // fall through
          case 74: break;
          case 36: 
            { return symbol (sym.SUBCLASS_OF_COLON, yytext());
            } 
            // fall through
          case 75: break;
          case 37: 
            { return symbol (sym.INDIVIDUALS_COLON, yytext());
            } 
            // fall through
          case 76: break;
          case 38: 
            { return symbol (sym.EQUIVALENT_TO_COLON, yytext());
            } 
            // fall through
          case 77: break;
          case 39: 
            { return symbol (sym.DISJOINT_CLASSES_COLON, yytext());
            } 
            // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
