package com.jongs.AnalisadorLex.Lex;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RIGHT_PAREN = 27;
  public static final int THAT = 8;
  public static final int DISJOINT_CLASSES_COLON = 16;
  public static final int CARDINALITY = 22;
  public static final int SOME = 2;
  public static final int RIGHT_BRACKET = 29;
  public static final int CLASS_IDENTIFIERS = 17;
  public static final int COMMENT = 23;
  public static final int CLASS_COLON = 12;
  public static final int DATA_TYPE = 21;
  public static final int GREATER_THAN = 30;
  public static final int WHITESPACE = 38;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int PROPERTY_IDENTIFIERS_HAS = 19;
  public static final int OR = 11;
  public static final int COMMA = 35;
  public static final int LEFT_BRACE = 24;
  public static final int BROKEN_LINE = 37;
  public static final int EQUIVALENT_TO_COLON = 13;
  public static final int MIN = 5;
  public static final int SSN = 40;
  public static final int EOF = 0;
  public static final int DOUBLE_QUOTE = 36;
  public static final int EQUAL = 32;
  public static final int error = 1;
  public static final int RIGHT_BRACE = 25;
  public static final int ONLY = 39;
  public static final int SUBCLASS_OF_COLON = 15;
  public static final int EQUAL_LESS_THAN = 33;
  public static final int EQUAL_GREATER_THAN = 34;
  public static final int EXACTLY = 7;
  public static final int LEFT_PAREN = 26;
  public static final int INDIVIDUALS_COLON = 14;
  public static final int ALL = 3;
  public static final int VALUE = 4;
  public static final int INDIVIDUAL_NAME = 18;
  public static final int LESS_THAN = 31;
  public static final int MAX = 6;
  public static final int LEFT_BRACKET = 28;
  public static final int PROPERTY_IDENTIFIERS_IS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SOME",
  "ALL",
  "VALUE",
  "MIN",
  "MAX",
  "EXACTLY",
  "THAT",
  "NOT",
  "AND",
  "OR",
  "CLASS_COLON",
  "EQUIVALENT_TO_COLON",
  "INDIVIDUALS_COLON",
  "SUBCLASS_OF_COLON",
  "DISJOINT_CLASSES_COLON",
  "CLASS_IDENTIFIERS",
  "INDIVIDUAL_NAME",
  "PROPERTY_IDENTIFIERS_HAS",
  "PROPERTY_IDENTIFIERS_IS",
  "DATA_TYPE",
  "CARDINALITY",
  "COMMENT",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_BRACKET",
  "RIGHT_BRACKET",
  "GREATER_THAN",
  "LESS_THAN",
  "EQUAL",
  "EQUAL_LESS_THAN",
  "EQUAL_GREATER_THAN",
  "COMMA",
  "DOUBLE_QUOTE",
  "BROKEN_LINE",
  "WHITESPACE",
  "ONLY",
  "SSN"
  };
}

